wordpress:
  wordpressPassword: foo
  mariadb:
    db:
      password: bar
    rootUser:
      password: baz
  service:
    type: ClusterIP
  ingress:
    enabled: true
    certManager: true
    hostname: wp.olm-voatsap.shalb.org
    annotations: {
      kubernetes.io/ingress.class: nginx,
      cert-manager.io/cluster-issuer: letsencrypt-prod
    }
    extraTls:
    - hosts:
      - wp.olm-voatsap.shalb.org
      secretName: wp.olm-voatsap.shalb.org
